class AppUrls {
  static String baseUrl="http://192.168.174.89:8000/social/";
  // static String baseUrl="http://10.129.235.89:8000/social/";
  // static String baseUrl="http://10.170.76.89:8000/social/";
  // static String baseUrl="http://10.246.24.89:8000/social/";
  // static String baseUrl="http://10.183.166.89:8000/social/";zz
  // static String baseUrl="http://10.14.125.89:8000/social/";
  // static String baseUrl="http://192.168.1.16:8000/social/";
  // static String baseUrl="http://172.17.237.89:8000/social/";
  // static String baseUrl="https://commonmodule.pythonanywhere.com/social/";
  static String post="post";
  static String getMapData="getMapData";
  static String tags="tags";
  static String userSearch="userSearch";
  static String locationSearch="locationSearch";
  static String googleLogin="googleLogin";
  static String emailLogin="emailLogin";
  static String emailSignUp="emailSignUp";
  static String forgotPassword="forgotPassword";
  static String verifyForgotPassword="verifyForgotPassword";
  static String resetPassword="resetPassword";
  static String generatePresignedUrl="generatePresignedUrl";
  static String userProfile="userProfile"; // myself
  static String like="like";
  static String story="story";
  static String storyViewCount="storyViewCount";
  static String comment="comment";
  static String replyComment="replyComment";
  static String likeComment="likeComment";
  static String savedPost="savedPost";
  static String city="city";
  static String analysis="analysis";
  static String poll="poll";
  static String vote="vote";
  static String userInfo="userInfo"; // other user
  static String follow="follow";
  static String unfollow="unfollow";
  static String tagPostByCity="tagPostByCity";
  static String tagsByCity="tagsByCity";
  static String cityByTag="cityByTag";
  static String notification="notification";
  static String markAllReadNotifications="markAllReadNotifications";
  static String trendingTags="trendingTags";
  static String getChatList="getChatList";
  static String getChatMessages="getChatMessages";
  static String sendMessage="sendMessage";
  static String deleteMessage="deleteMessage";
  static String contact="contact";
  static String feedback="feedback";
  static String getMutualFromContacts="getMutualFromContacts";
}

